name: CI/CD
on:
  push:
    branches:
      - main

jobs:
  prepare-env:
    name: Prepare environment
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
  test:
    name: Test
    runs-on: ubuntu-latest
    needs: [ prepare-env ]
    timeout-minutes: 5
    steps:
      - name: Test order generator
        run: ./gradlew -p order-generator clean test
      - name: Test order validator
        run: ./gradlew -p order-validator clean test
  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [ test ]
    timeout-minutes: 5
    steps:
      - name: Build order generator
        run: ./gradlew -p order-generator clean build -x test
      - name: Upload order generator artifact
        uses: actions/upload-artifact@v2
        with:
          name: build-order-generator
          path: order-generator/build/libs/order-generator-0.0.1-SNAPSHOT.jar
      - name: Build order validator
        run: ./gradlew -p order-validator clean build -x test
      - name: Upload order validator artifact
        uses: actions/upload-artifact@v2
        with:
          name: build-order-validator
          path: order-validator/build/libs/order-validator-0.0.1-SNAPSHOT.jar
  push_to_registry:
    name: Push Docker images to Docker Hub
    runs-on: ubuntu-latest
    needs: [ build ]
    steps:
      - uses: actions/checkout@v2
      - name: Download order-generator build artifact
        uses: actions/download-artifact@v2
        with:
          name: build-order-generator
          path: order-generator/build/libs
      - name: Download order-validator build artifact
        uses: actions/download-artifact@v2
        with:
          name: build-order-validator
          path: order-validator/build/libs
      - name: Push order-generator to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          path: order-generator
          repository: dodalovic/order-generator
          tag_with_ref: true
      - name: Push order-validator to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          path: order-validator
          repository: dodalovic/order-validator
          tag_with_ref: true